# Dependabot version updates for AdventureLog.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/backend/server"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/documentation"
    schedule:
      interval: weekly
