services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: adventurelog-frontend:dev
    container_name: adventurelog-frontend
    restart: unless-stopped
    user: root
    env_file: .env
    environment:
      - CI=true
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-8015}:3000"
    depends_on:
      - server
    volumes:
      - ./frontend:/app
      - pnpm_store:/pnpm-store

  db:
    image: docker.io/postgis/postgis:16-3.5
    container_name: adventurelog-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: adventurelog-backend:dev
    container_name: adventurelog-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_ADMIN_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_ADMIN_EMAIL}
    ports:
      - "127.0.0.1:${BACKEND_PORT:-8016}:8000"
    depends_on:
      - db
    volumes:
      - ./backend/server:/code
      - ./backend/entrypoint.sh:/code/entrypoint.sh:rw
      - adventurelog_media:/code/media/

volumes:
  postgres_data:
  adventurelog_media:
  pnpm_store: