# Generated by Django 5.2.6 on 2025-11-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketitem',
            name='is_public',
        ),
    ]
