# Generated by Django 5.0.8 on 2024-08-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
