# Generated by Django 5.0.8 on 2024-08-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0002_region_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
