# Generated by Django 5.0.8 on 2024-08-23 17:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0003_alter_region_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
