# Generated by Django 5.0.8 on 2024-08-23 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0004_country_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='geometry',
        ),
        migrations.AddField(
            model_name='region',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
