# Generated by Django 5.0.8 on 2024-09-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0005_remove_country_geometry_region_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
