# Generated by Django 5.0.8 on 2024-09-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0006_remove_country_continent_country_subregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_en',
        ),
    ]
