# Generated by Django 5.0.8 on 2024-09-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0008_region_latitude_region_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
