# Generated by Django 5.0.8 on 2025-01-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0013_visitedcity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitedcity',
            options={'verbose_name_plural': 'Visited Cities'},
        ),
    ]
