# Generated by Django 5.0.8 on 2025-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0015_city_insert_id_country_insert_id_region_insert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='translations',
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
