# Generated by Django 5.2.1 on 2025-06-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0015_city_insert_id_country_insert_id_region_insert_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='insert_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='insert_id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='insert_id',
        ),
    ]
