# Generated by Django 5.2.1 on 2025-06-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0016_remove_city_insert_id_remove_country_insert_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedregion',
            old_name='user_id',
            new_name='user',
        ),
    ]
