# Generated by Django 5.2.1 on 2025-06-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravel', '0017_rename_user_id_visitedregion_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedcity',
            old_name='user_id',
            new_name='user',
        ),
    ]
