# Generated by Django 5.0.8 on 2024-08-15 23:20

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', 'migrate_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='images/'),
        ),
    ]
