# Generated by Django 5.0.6 on 2024-06-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
