# Generated by Django 5.0.8 on 2024-09-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', 'migrate_visits_and_categories'),
        ('adventures', 'migrate_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='date',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='image',
        ),
    ]
