# Generated by Django 5.0.8 on 2024-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_alter_adventureimage_adventure'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
