# Generated by Django 5.0.8 on 2024-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_collection_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='link',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
