# Generated by Django 5.0.6 on 2024-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_remove_adventure_trip_id_trip_adventure_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='type',
            field=models.CharField(choices=[('visited', 'Visited'), ('planned', 'Planned'), ('featured', 'Featured')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('visited', 'Visited'), ('planned', 'Planned'), ('featured', 'Featured')], max_length=100),
        ),
    ]
