# Generated by Django 5.0.8 on 2024-09-23 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', 'migrate_visits_categories'),
        ('adventures', 'migrate_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='date',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='image',
        ),
    ]
