# Generated by Django 5.0.6 on 2024-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0007_remove_adventure_trip_alter_adventure_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
