# Generated by Django 5.0.8 on 2024-10-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0009_alter_adventure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='link',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
