# Generated by Django 5.0.6 on 2024-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0010_adventure_created_at_collection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
