# Generated by Django 5.0.7 on 2024-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0011_adventure_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
