# Generated by Django 5.0.7 on 2024-08-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0014_alter_transportation_type_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
