# Generated by Django 5.0.7 on 2024-08-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0015_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
