# Generated by Django 5.0.8 on 2025-01-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0016_alter_adventureimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
