# Generated by Django 5.0.8 on 2025-01-19 22:17

import adventures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0018_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=adventures.models.PathAndRename('attachments/')),
        ),
    ]
