# Generated by Django 5.0.8 on 2025-01-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0019_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
