# Generated by Django 5.0.8 on 2025-01-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0020_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
