# Generated by Django 5.0.7 on 2024-08-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0020_checklist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
