# Generated by Django 5.0.11 on 2025-02-02 14:59

import adventures.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0021_alter_attachment_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureimage',
            name='external_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='adventureimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to=adventures.models.PathAndRename('images/')),
        ),
        migrations.AddConstraint(
            model_name='adventureimage',
            constraint=models.CheckConstraint(check=models.Q(('image__exact', ''), ('external_url__isnull', True), _connector='XOR'), name='image_xor_external_url'),
        ),
    ]
