# Generated by Django 5.0.8 on 2025-03-17 01:15

import adventures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0023_lodging_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=adventures.models.PathAndRename('attachments/'), validators=[adventures.models.validate_file_extension]),
        ),
    ]
