# Generated by Django 5.0.8 on 2025-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0024_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
