# Generated by Django 5.0.11 on 2025-05-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0028_lodging_timezone'),
        ('worldtravel', '0015_city_insert_id_country_insert_id_region_insert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldtravel.city'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldtravel.country'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldtravel.region'),
        ),
    ]
