# Generated by Django 5.2.1 on 2025-05-24 14:59

import adventures.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0029_adventure_city_adventure_country_adventure_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureimage',
            name='external_url',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='adventureimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to=adventures.models.PathAndRename('images/')),
        ),
    ]
