# Generated by Django 5.2.1 on 2025-06-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0031_adventureimage_immich_id_alter_adventureimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adventureimage',
            name='image_xor_immich_id',
        ),
    ]
