# Generated by Django 5.2.1 on 2025-06-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0033_adventureimage_unique_immich_id_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adventureimage',
            name='unique_immich_id_per_user',
        ),
    ]
