# Generated by Django 5.2.1 on 2025-06-19 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('adventures', '0036_rename_adventure_location'), ('adventures', '0037_rename_adventure_visit_location'), ('adventures', '0038_rename_adventureimage_locationimage'), ('adventures', '0039_rename_adventure_locationimage_location'), ('adventures', '0040_rename_adventure_attachment_location'), ('adventures', '0041_rename_user_id_location_user'), ('adventures', '0042_rename_user_id_locationimage_user'), ('adventures', '0043_rename_user_id_attachment_user'), ('adventures', '0044_rename_user_id_collection_user'), ('adventures', '0045_rename_user_id_transportation_user'), ('adventures', '0046_rename_user_id_note_user'), ('adventures', '0047_rename_user_id_checklist_user'), ('adventures', '0048_rename_user_id_checklistitem_user'), ('adventures', '0049_rename_user_id_category_user'), ('adventures', '0050_rename_user_id_lodging_user')]

    dependencies = [
        ('adventures', '0035_remove_adventure_collection_adventure_collections'),
        ('worldtravel', '0016_remove_city_insert_id_remove_country_insert_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adventure',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='adventure',
            new_name='location',
        ),
        migrations.RenameModel(
            old_name='AdventureImage',
            new_name='LocationImage',
        ),
        migrations.RenameField(
            model_name='locationimage',
            old_name='adventure',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='adventure',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='locationimage',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lodging',
            old_name='user_id',
            new_name='user',
        ),
    ]
