# Generated by Django 5.2.1 on 2025-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0036_rename_adventure_location_squashed_0050_rename_user_id_lodging_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='activity_types',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='location',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='locations', to='adventures.collection'),
        ),
    ]
