# Generated by Django 5.2.1 on 2025-07-10 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0051_rename_activity_types_location_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='ContentAttachment',
        ),
        migrations.RenameModel(
            old_name='LocationImage',
            new_name='ContentImage',
        ),
    ]
