# Generated by Django 5.2.1 on 2025-07-10 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0052_rename_attachment_contentattachment_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentattachment',
            options={'verbose_name': 'Content Attachment', 'verbose_name_plural': 'Content Attachments'},
        ),
        migrations.AlterModelOptions(
            name='contentimage',
            options={'verbose_name': 'Content Image', 'verbose_name_plural': 'Content Images'},
        ),
        migrations.AddField(
            model_name='contentattachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentattachment',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contentattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='adventures__content_e42b72_idx'),
        ),
        migrations.AddIndex(
            model_name='contentimage',
            index=models.Index(fields=['content_type', 'object_id'], name='adventures__content_aa4984_idx'),
        ),
    ]
