# Generated by Django 5.2.1 on 2025-07-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0054_migrate_location_images_generic_relation'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentattachment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contentimage',
            name='location',
        ),
        migrations.AlterField(
            model_name='contentattachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_attachments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contentattachment',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
