# Generated by Django 5.2.2 on 2025-08-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0058_alter_collectioninvite_options_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
