# Generated by Django 5.2.2 on 2025-08-07 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0059_alter_activity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectioninvite',
            unique_together={('collection', 'invited_user')},
        ),
    ]
