# Generated by Django 5.2.8 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0071_alter_collectionitineraryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date_precision',
            field=models.CharField(
                choices=[
                    ('full', 'Full date (day-month-year)'),
                    ('month', 'Month and year only'),
                    ('year', 'Year only'),
                ],
                default='full',
                help_text='Precision level of the visit date: full, month, or year',
                max_length=10,
            ),
        ),
    ]
