# Generated by Django 5.2.13 on 2026-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0076_normalize_all_day_visit_end_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('plane', 'Plane'), ('train', 'Train'), ('bus', 'Bus'), ('boat', 'Boat'), ('bike', 'Bike'), ('walking', 'Walking'), ('other', 'Other')], max_length=100),
        ),
    ]
