INSERT INTO "featuredAdventures" (id, name, location) VALUES
  (20, 'Yellowstone National Park', 'Wyoming, Montana, Idaho, USA'),
  (21, 'Yosemite National Park', 'California, USA'),
  (22, 'Banff National Park', 'Alberta, Canada'),
  (23, 'Kruger National Park', 'Limpopo, South Africa'),
  (24, 'Grand Canyon National Park', 'Arizona, USA'),
  (25, 'Great Smoky Mountains National Park', 'North Carolina, Tennessee, USA'),
  (26, 'Zion National Park', 'Utah, USA'),
  (27, 'Glacier National Park', 'Montana, USA'),
  (28, 'Rocky Mountain National Park', 'Colorado, USA'),
  (29, 'Everglades National Park', 'Florida, USA'),
  (30, 'Arches National Park', 'Utah, USA'),
  (31, 'Acadia National Park', 'Maine, USA'),
  (32, 'Sequoia National Park', 'California, USA'),
  (33, 'Joshua Tree National Park', 'California, USA'),
  (34, 'Yellowstone National Park', 'Wyoming, Montana, Idaho, USA'),
  (35, 'Bryce Canyon National Park', 'Utah, USA'),
  (36, 'Grand Teton National Park', 'Wyoming, USA'),
  (37, 'Denali National Park', 'Alaska, USA'),
  (38, 'Olympic National Park', 'Washington, USA'),
  (39, 'Canyonlands National Park', 'Utah, USA'),
  (40, 'Death Valley National Park', 'California, Nevada, USA'),
  (41, 'Redwood National and State Parks', 'California, USA'),
  (42, 'Waterton Lakes National Park', 'Alberta, Canada'),
  (43, 'Mesa Verde National Park', 'Colorado, USA'),
  (44, 'Petrified Forest National Park', 'Arizona, USA'),
  (45, 'Capitol Reef National Park', 'Utah, USA'),
  (46, 'Yellowstone National Park', 'Wyoming, Montana, Idaho, USA'),
  (47, 'Yosemite National Park', 'California, USA'),
  (48, 'Banff National Park', 'Alberta, Canada'),
  (49, 'Kruger National Park', 'Limpopo, South Africa'),
  (50, 'Grand Canyon National Park', 'Arizona, USA'),
  (51, 'Great Smoky Mountains National Park', 'North Carolina, Tennessee, USA'),
  (52, 'Zion National Park', 'Utah, USA'),
  (53, 'Glacier National Park', 'Montana, USA'),
  (54, 'Rocky Mountain National Park', 'Colorado, USA'),
  (55, 'Everglades National Park', 'Florida, USA'),
  (56, 'Arches National Park', 'Utah, USA'),
  (57, 'Acadia National Park', 'Maine, USA'),
  (58, 'Sequoia National Park', 'California, USA'),
  (59, 'Joshua Tree National Park', 'California, USA'),
  (60, 'Yellowstone National Park', 'Wyoming, Montana, Idaho, USA'),
  (61, 'Bryce Canyon National Park', 'Utah, USA'),
  (62, 'Grand Teton National Park', 'Wyoming, USA'),
  (63, 'Denali National Park', 'Alaska, USA'),
  (64, 'Olympic National Park', 'Washington, USA'),
  (65, 'Canyonlands National Park', 'Utah, USA'),
  (66, 'Yellowstone National Park', 'Wyoming, Montana, Idaho, USA'),
  (67, 'Yosemite National Park', 'California, USA'),
  (68, 'Banff National Park', 'Alberta, Canada'),
  (69, 'Kruger National Park', 'Limpopo, South Africa'),
  (70, 'Grand Canyon National Park', 'Arizona, USA'),
  (71, 'Great Smoky Mountains National Park', 'North Carolina, Tennessee, USA'),
  (72, 'Zion National Park', 'Utah, USA'),
  (73, 'Glacier National Park', 'Montana, USA'),
  (74, 'Rocky Mountain National Park', 'Colorado, USA'),
  (75, 'Everglades National Park', 'Florida, USA'),
  (76, 'Arches National Park', 'Utah, USA'),
  (77, 'Acadia National Park', 'Maine, USA'),
  (78, 'Sequoia National Park', 'California, USA'),
  (79, 'Joshua Tree National Park', 'California, USA'),
  (80, 'Yellowstone National Park', 'Wyoming, Montana, Idaho, USA'),
  (81, 'Bryce Canyon National Park', 'Utah, USA'),
  (82, 'Grand Teton National Park', 'Wyoming, USA'),
  (83, 'Denali National Park', 'Alaska, USA'),
  (84, 'Olympic National Park', 'Washington, USA'),
  (85, 'Canyonlands National Park', 'Utah, USA'),
  (86, 'Yellowstone National Park', 'Wyoming, Montana, Idaho, USA'),
  (87, 'Yosemite National Park', 'California, USA'),
  (88, 'Banff National Park', 'Alberta, Canada'),
  (89, 'Kruger National Park', 'Limpopo, South Africa'),
  (90, 'Grand Canyon National Park', 'Arizona, USA'),
  (91, 'Great Smoky Mountains National Park', 'North Carolina, Tennessee, USA'),
  (92, 'Zion National Park', 'Utah, USA'),
  (93, 'Glacier National Park', 'Montana, USA'),
  (94, 'Rocky Mountain National Park', 'Colorado, USA'),
  (95, 'Everglades National Park', 'Florida, USA'),
  (96, 'Arches National Park', 'Utah, USA'),
  (97, 'Acadia National Park', 'Maine, USA'),
  (98, 'Sequoia National Park', 'California, USA'),
  (99, 'Joshua Tree National Park', 'California, USA');
