# Generated by Django 5.2.1 on 2025-06-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immichintegration',
            name='copy_locally',
            field=models.BooleanField(default=True, help_text='Copy image to local storage, instead of just linking to the remote URL.'),
        ),
    ]
