# Generated by Django 5.2.2 on 2025-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_wandererintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wandererintegration',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
