# Generated by Django 5.2.2 on 2025-08-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_wandererintegration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wandererintegration',
            name='token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
