# Generated by Django 5.2.13 on 2026-07-09 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_wandererintegration_api_key_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndurainIntegration',
            fields=[
                ('server_url', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(max_length=2048)),
                ('access_token_expires_at', models.BigIntegerField()),
                ('refresh_token_expires_at', models.BigIntegerField(blank=True, null=True)),
                ('endurain_user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('sso', 'SSO')], default='password', max_length=16)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endurain_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endurain Integration',
                'verbose_name_plural': 'Endurain Integrations',
            },
        ),
    ]
