# Generated by Django 5.2.13 on 2026-07-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_endurainintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endurainintegration',
            name='auth_method',
            field=models.CharField(choices=[('password', 'Password')], default='password', max_length=16),
        ),
    ]
