# Generated by Django 5.0.8 on 2025-03-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disable_password',
            field=models.BooleanField(default=False),
        ),
    ]
