# Generated by Django 5.2.2 on 2025-08-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_disable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='measurement_system',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10),
        ),
    ]
