# Generated by Django 5.2.11 on 2026-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_map_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='map_style',
            field=models.CharField(choices=[('default', 'Default'), ('terrain-3d', '3D Terrain'), ('satellite-terrain-3d', '3D Satellite Terrain'), ('topo-terrain-3d', '3D Topographic'), ('osm-standard', 'OpenStreetMap'), ('satellite', 'Satellite'), ('satellite-labels', 'Satellite + Labels'), ('usgs-imagery', 'USGS Imagery'), ('usgs-imagery-topo', 'USGS Imagery + Topo'), ('elevation', 'Elevation'), ('usgs-topo', 'USGS Topo'), ('esri-topo', 'Esri Topo'), ('opentopomap', 'OpenTopoMap'), ('carto-light', 'Light'), ('carto-dark', 'Dark'), ('carto-positron', 'Positron'), ('carto-positron-labels', 'Positron + Labels'), ('esri-gray', 'Gray Canvas'), ('carto-voyager', 'Voyager'), ('osm-humanitarian', 'Humanitarian'), ('esri-streets', 'Streets'), ('esri-national-geographic', 'National Geographic'), ('esri-oceans', 'Oceans'), ('osm-france', 'France Style'), ('openfreemap-liberty', 'OpenFreeMap Liberty')], default='default', max_length=32),
        ),
    ]
