# Generated by Django 5.2.13 on 2026-08-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_map_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legal_consent',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
