# Generated by Django 5.2.13 on 2026-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_legal_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_format',
            field=models.CharField(choices=[('locale', 'Browser default'), ('mdy', 'MM/DD/YYYY'), ('dmy', 'DD/MM/YYYY'), ('ymd', 'YYYY-MM-DD')], default='locale', max_length=10),
        ),
    ]
