# Generated by Django 5.0.8 on 2025-02-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='key',
            field=models.CharField(default='achievements.other', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('adventure_count', 'adventure_count'), ('country_count', 'country_count')], default='adventure_count', max_length=255),
        ),
    ]
