<script lang="ts">
	import { getBasemapUrl } from '$lib';
	import { appVersion } from '$lib/config';
	import { addToast } from '$lib/toasts';
	import type { Location, Lodging, GeocodeSearchResult, Point, ReverseGeocode } from '$lib/types';
	import { onMount } from 'svelte';
	import { t } from 'svelte-i18n';
	import { DefaultMarker, MapEvents, MapLibre } from 'svelte-maplibre';

	export let item: Location | Lodging;
	export let triggerMarkVisted: boolean = false;

	export let initialLatLng: { lat: number; lng: number } | null = null; // Used to pass the location from the map selection to the modal

	let reverseGeocodePlace: ReverseGeocode | null = null;
	let markers: Point[] = [];

	let query: string = '';
	let is_custom_location: boolean = false;
	let willBeMarkedVisited: boolean = false;
	let previousCoords: { lat: number; lng: number } | null = null;
	let old_display_name: string = '';
	let places: GeocodeSearchResult[] = [];
	let noPlaces: boolean = false;

	let isNameAutoGenerated: boolean = false;

	onMount(() => {
		if (initialLatLng) {
			markers = [
				{
					lngLat: { lng: initialLatLng.lng, lat: initialLatLng.lat },
					name: '',
					location: '',
					activity_type: ''
				}
			];
			item.latitude = initialLatLng.lat;
			item.longitude = initialLatLng.lng;
			reverseGeocode();
		}
	});

	$: if (markers.length > 0) {
		const newLat = Math.round(markers[0].lngLat.lat * 1e6) / 1e6;
		const newLng = Math.round(markers[0].lngLat.lng * 1e6) / 1e6;

		if (!previousCoords || previousCoords.lat !== newLat || previousCoords.lng !== newLng) {
			item.latitude = newLat;
			item.longitude = newLng;
			previousCoords = { lat: newLat, lng: newLng };
			reverseGeocode();
		}

		// if (!item.name) {
		// 	item.name = markers[0].name;
		// }
	}

	$: if (triggerMarkVisted && willBeMarkedVisited) {
		displaySuccessToast(); // since the server will trigger the geocode automatically, we just need to show the toast and let the server handle the rest. It's kinda a placebo effect
		triggerMarkVisted = false;
	}

	$: {
		is_custom_location = Boolean(
			item.location != reverseGeocodePlace?.display_name && item.location
		);
	}

	if (item.longitude && item.latitude) {
		markers = [];
		markers = [
			{
				lngLat: { lng: item.longitude, lat: item.latitude },
				location: item.location || '',
				name: item.name,
				activity_type: ''
			}
		];
	}

	$: {
		if ('visits' in item) {
			willBeMarkedVisited = false; // Reset before evaluating

			const today = new Date(); // Cache today's date to avoid redundant calculations

			for (const visit of item.visits) {
				const startDate = new Date(visit.start_date);
				const endDate = visit.end_date ? new Date(visit.end_date) : null;

				// If the visit has both a start date and an end date, check if it started by today
				if (startDate && endDate && startDate <= today) {
					willBeMarkedVisited = true;
					break; // Exit the loop since we've determined the result
				}

				// If the visit has a start date but no end date, check if it started by today
				if (startDate && !endDate && startDate <= today) {
					willBeMarkedVisited = true;
					break; // Exit the loop since we've determined the result
				}
			}
		}
	}

	function displaySuccessToast() {
		if (reverseGeocodePlace) {
			if (reverseGeocodePlace.region) {
				addToast('success', `Visit to ${reverseGeocodePlace.region} marked`);
			}
			if (reverseGeocodePlace.city) {
				addToast('success', `Visit to ${reverseGeocodePlace.city} marked`);
			}
		}
	}

	async function markVisited() {
		console.log(reverseGeocodePlace);
		if (reverseGeocodePlace) {
			if (!reverseGeocodePlace.region_visited && reverseGeocodePlace.region_id) {
				let region_res = await fetch(`/api/visitedregion`, {
					headers: { 'Content-Type': 'application/json' },
					method: 'POST',
					body: JSON.stringify({ region: reverseGeocodePlace.region_id })
				});
				if (region_res.ok) {
					reverseGeocodePlace.region_visited = true;
					addToast('success', `Visit to ${reverseGeocodePlace.region} marked`);
				} else {
					addToast('error', `Failed to mark visit to ${reverseGeocodePlace.region}`);
				}
			}
			if (!reverseGeocodePlace.city_visited && reverseGeocodePlace.city_id != null) {
				let city_res = await fetch(`/api/visitedcity`, {
					headers: { 'Content-Type': 'application/json' },
					method: 'POST',
					body: JSON.stringify({ city: reverseGeocodePlace.city_id })
				});
				if (city_res.ok) {
					reverseGeocodePlace.city_visited = true;
					addToast('success', `Visit to ${reverseGeocodePlace.city} marked`);
				} else {
					addToast('error', `Failed to mark visit to ${reverseGeocodePlace.city}`);
				}
			}
		}
	}

	async function addMarker(e: CustomEvent<any>) {
		markers = [];
		markers = [
			...markers,
			{
				lngLat: e.detail.lngLat,
				name: '',
				location: '',
				activity_type: ''
			}
		];
		console.log(markers);
	}

	async function geocode(e: Event | null) {
		if (e) {
			e.preventDefault();
		}
		if (!query) {
			alert($t('adventures.no_location'));
			return;
		}
		let res = await fetch(`/api/reverse-geocode/search/?query=${query}`);
		console.log(res);
		let data = (await res.json()) as GeocodeSearchResult[] | { error: string };

		if ('error' in data) {
			places = [];
			noPlaces = true;
		} else {
			places = data;
			if (data.length === 0) {
				noPlaces = true;
			} else {
				noPlaces = false;
			}
		}
	}

	async function reverseGeocode(force_update: boolean = false) {
		let res = await fetch(
			`/api/reverse-geocode/reverse_geocode/?lat=${item.latitude}&lon=${item.longitude}`
		);
		let data = await res.json();
		if (data.error) {
			console.log(data.error);
			reverseGeocodePlace = null;
			return;
		}
		reverseGeocodePlace = data;

		console.log(reverseGeocodePlace);
		console.log(is_custom_location);

		if (
			reverseGeocodePlace &&
			reverseGeocodePlace.display_name &&
			(!is_custom_location || force_update)
		) {
			old_display_name = reverseGeocodePlace.display_name;
			item.location = reverseGeocodePlace.display_name;
			if (reverseGeocodePlace.location_name && !item.name) {
				item.name = reverseGeocodePlace.location_name;
			}
		}
		console.log(data);
	}

	function clearMap() {
		console.log('CLEAR');
		markers = [];
		item.latitude = null;
		item.longitude = null;
	}
</script>

<!-- Location Information Section -->
<div
	class="collapse collapse-plus bg-base-200/50 border border-base-300/50 mb-6 rounded-2xl overflow-hidden"
>
	<input type="checkbox" checked />
	<div class="collapse-title text-xl font-semibold bg-gradient-to-r from-primary/10 to-primary/5">
		<div class="flex items-center gap-3">
			<div class="p-2 bg-primary/10 rounded-lg">
				<svg class="w-5 h-5 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
					/>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
					/>
				</svg>
			</div>
			{$t('adventures.location_information')}
		</div>
	</div>
	<div class="collapse-content bg-base-100/50 p-6 space-y-6">
		<!-- Location Name Input -->
		<div class="form-control">
			<label class="label">
				<span class="label-text font-medium">{$t('adventures.display_name')}</span>
			</label>
			<div class="flex items-center gap-3">
				<input
					type="text"
					id="location"
					name="location"
					bind:value={item.location}
					class="input input-bordered flex-1 bg-base-100/80 focus:bg-base-100"
					placeholder="Boston, MA, US"
				/>
				{#if is_custom_location}
					<button
						class="btn btn-primary gap-2"
						type="button"
						on:click={() => (item.location = reverseGeocodePlace?.display_name)}
					>
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
							/>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
							/>
						</svg>
						{$t('adventures.set_to_pin')}
					</button>
				{/if}
			</div>
		</div>

		<!-- Location Search -->
		<div class="form-control">
			<label class="label">
				<span class="label-text font-medium">{$t('adventures.search_location')}</span>
			</label>
			<form on:submit={geocode} class="flex flex-col sm:flex-row gap-3">
				<div class="relative flex-1">
					<svg
						class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-base-content/40"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
						/>
					</svg>
					<input
						type="text"
						placeholder={$t('adventures.search_for_location')}
						class="input input-bordered w-full pl-10 bg-base-100/80 focus:bg-base-100"
						id="search"
						name="search"
						bind:value={query}
					/>
				</div>
				<div class="flex gap-2">
					<button class="btn btn-neutral gap-2" type="submit">
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
							/>
						</svg>
						{$t('navbar.search')}
					</button>
					<button class="btn btn-neutral btn-outline gap-2" type="button" on:click={clearMap}>
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
							/>
						</svg>
						{$t('adventures.clear_map')}
					</button>
				</div>
			</form>
		</div>

		<!-- Search Results -->
		{#if places.length > 0}
			<div class="form-control">
				<label class="label">
					<span class="label-text font-medium flex items-center gap-2">
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
							/>
						</svg>
						{$t('adventures.search_results')}
					</span>
				</label>
				<div
					class="grid grid-cols-1 sm:grid-cols-2 gap-3 p-4 bg-base-100/80 border border-base-300 rounded-xl max-h-60 overflow-y-auto"
				>
					{#each places as place}
						<button
							type="button"
							class="btn btn-ghost btn-sm h-auto min-h-0 p-3 justify-start text-left hover:bg-base-200"
							on:click={() => {
								markers = [
									{
										lngLat: { lng: Number(place.lon), lat: Number(place.lat) },
										location: place.display_name ?? '',
										name: place.name ?? '',
										activity_type: place.type ?? ''
									}
								];
								if (isNameAutoGenerated || !item.name) {
									item.name = place.name ?? '';
									isNameAutoGenerated = true;
								}
							}}
						>
							<div class="flex flex-col items-start w-full">
								<span class="font-medium text-sm">{place.name}</span>
								<small class="text-xs text-base-content/60 truncate w-full"
									>{place.display_name}</small
								>
							</div>
						</button>
					{/each}
				</div>
			</div>
		{:else if noPlaces}
			<div class="alert alert-error">
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
					/>
				</svg>
				<span>{$t('adventures.no_results')}</span>
			</div>
		{/if}

		<!-- Map Container -->
		<div class="form-control">
			<label class="label">
				<span class="label-text font-medium flex items-center gap-2">
					<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"
						/>
					</svg>
					{$t('worldtravel.interactive_map')}
				</span>
			</label>
			<div class="bg-base-100/80 border border-base-300 rounded-xl p-4">
				<MapLibre
					style={getBasemapUrl()}
					class="relative aspect-[9/16] max-h-[70vh] w-full sm:aspect-video sm:max-h-full rounded-lg border border-base-300"
					standardControls
					zoom={item.latitude && item.longitude ? 12 : 1}
					center={{ lng: item.longitude || 0, lat: item.latitude || 0 }}
				>
					<MapEvents on:click={addMarker} />
					{#each markers as marker}
						<DefaultMarker lngLat={marker.lngLat} />
					{/each}
				</MapLibre>
			</div>
		</div>

		<!-- Location Details -->
		{#if reverseGeocodePlace}
			<div class="bg-gradient-to-r from-info/10 to-info/5 border border-info/20 rounded-xl p-6">
				<h3 class="text-lg font-bold flex items-center gap-2 mb-4">
					<div class="p-2 bg-info/10 rounded-lg">
						<svg class="w-5 h-5 text-info" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
							/>
						</svg>
					</div>
					{$t('adventures.location_details')}
				</h3>

				<div class="space-y-3">
					<div class="flex items-center gap-3 p-3 bg-base-100/50 rounded-lg">
						<svg
							class="w-4 h-4 text-base-content/60"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.99 1.99 0 013 12V7a4 4 0 014-4z"
							/>
						</svg>
						<span class="font-medium text-sm">{$t('adventures.display_name')}:</span>
						<span class="text-sm">
							{reverseGeocodePlace.city
								? reverseGeocodePlace.city + ', '
								: ''}{reverseGeocodePlace.region}, {reverseGeocodePlace.country}
						</span>
					</div>

					<div class="flex items-center gap-3 p-3 bg-base-100/50 rounded-lg">
						<svg
							class="w-4 h-4 text-base-content/60"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
							/>
						</svg>
						<span class="font-medium text-sm">{$t('adventures.region')}:</span>
						<span class="text-sm">{reverseGeocodePlace.region}</span>
						<div class="ml-auto">
							{#if reverseGeocodePlace.region_visited}
								<div class="badge badge-success badge-sm gap-1">
									<svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M5 13l4 4L19 7"
										/>
									</svg>
									{$t('adventures.visited')}
								</div>
							{:else}
								<div class="badge badge-error badge-sm gap-1">
									<svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M6 18L18 6M6 6l12 12"
										/>
									</svg>
									{$t('adventures.not_visited')}
								</div>
							{/if}
						</div>
					</div>

					{#if reverseGeocodePlace.city}
						<div class="flex items-center gap-3 p-3 bg-base-100/50 rounded-lg">
							<svg
								class="w-4 h-4 text-base-content/60"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"
								/>
							</svg>
							<span class="font-medium text-sm">{$t('adventures.city')}:</span>
							<span class="text-sm">{reverseGeocodePlace.city}</span>
							<div class="ml-auto">
								{#if reverseGeocodePlace.city_visited}
									<div class="badge badge-success badge-sm gap-1">
										<svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M5 13l4 4L19 7"
											/>
										</svg>
										{$t('adventures.visited')}
									</div>
								{:else}
									<div class="badge badge-error badge-sm gap-1">
										<svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M6 18L18 6M6 6l12 12"
											/>
										</svg>
										{$t('adventures.not_visited')}
									</div>
								{/if}
							</div>
						</div>
					{/if}
				</div>

				<!-- Mark Visited Button -->
				{#if !reverseGeocodePlace.region_visited || (!reverseGeocodePlace.city_visited && !willBeMarkedVisited)}
					<button type="button" class="btn btn-primary gap-2 mt-4" on:click={markVisited}>
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M5 13l4 4L19 7"
							/>
						</svg>
						{$t('adventures.mark_visited')}
					</button>
				{/if}

				<!-- Will be marked visited alert -->
				{#if (willBeMarkedVisited && !reverseGeocodePlace.region_visited && reverseGeocodePlace.region_id) || (!reverseGeocodePlace.city_visited && willBeMarkedVisited && reverseGeocodePlace.city_id)}
					<div class="alert alert-info mt-4">
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
							/>
						</svg>
						<div>
							<h4 class="font-bold">{$t('adventures.location_will_be_marked')}</h4>
							<div class="text-sm">
								{reverseGeocodePlace.city
									? reverseGeocodePlace.city + ', '
									: ''}{reverseGeocodePlace.region}, {reverseGeocodePlace.country}
								{$t('adventures.will_be_marked_location')}
							</div>
						</div>
					</div>
				{/if}
			</div>
		{/if}
	</div>
</div>
