INSERT INTO "worldTravelCountryRegions" (id, name, country_code)
VALUES
  ('US-AL', 'Alabama', 'us'),
  ('US-AK', 'Alaska', 'us'),
  ('US-AZ', 'Arizona', 'us'),
  ('US-AR', 'Arkansas', 'us'),
  ('US-CA', 'California', 'us'),
  ('US-CO', 'Colorado', 'us'),
  ('US-CT', 'Connecticut', 'us'),
  ('US-DE', 'Delaware', 'us'),
  ('US-FL', 'Florida', 'us'),
  ('US-GA', 'Georgia', 'us'),
  ('US-HI', 'Hawaii', 'us'),
  ('US-ID', 'Idaho', 'us'),
  ('US-IL', 'Illinois', 'us'),
  ('US-IN', 'Indiana', 'us'),
  ('US-IA', 'Iowa', 'us'),
  ('US-KS', 'Kansas', 'us'),
  ('US-KY', 'Kentucky', 'us'),
  ('US-LA', 'Louisiana', 'us'),
  ('US-ME', 'Maine', 'us'),
  ('US-MD', 'Maryland', 'us'),
  ('US-MA', 'Massachusetts', 'us'),
  ('US-MI', 'Michigan', 'us'),
  ('US-MN', 'Minnesota', 'us'),
  ('US-MS', 'Mississippi', 'us'),
  ('US-MO', 'Missouri', 'us'),
  ('US-MT', 'Montana', 'us'),
  ('US-NE', 'Nebraska', 'us'),
  ('US-NV', 'Nevada', 'us'),
  ('US-NH', 'New Hampshire', 'us'),
  ('US-NJ', 'New Jersey', 'us'),
  ('US-NM', 'New Mexico', 'us'),
  ('US-NY', 'New York', 'us'),
  ('US-NC', 'North Carolina', 'us'),
  ('US-ND', 'North Dakota', 'us'),
  ('US-OH', 'Ohio', 'us'),
  ('US-OK', 'Oklahoma', 'us'),
  ('US-OR', 'Oregon', 'us'),
  ('US-PA', 'Pennsylvania', 'us'),
  ('US-RI', 'Rhode Island', 'us'),
  ('US-SC', 'South Carolina', 'us'),
  ('US-SD', 'South Dakota', 'us'),
  ('US-TN', 'Tennessee', 'us'),
  ('US-TX', 'Texas', 'us'),
  ('US-UT', 'Utah', 'us'),
  ('US-VT', 'Vermont', 'us'),
  ('US-VA', 'Virginia', 'us'),
  ('US-WA', 'Washington', 'us'),
  ('US-WV', 'West Virginia', 'us'),
  ('US-WI', 'Wisconsin', 'us'),
  ('US-WY', 'Wyoming', 'us')
ON CONFLICT (id) DO NOTHING;
