INSERT INTO "worldTravelCountryRegions" (id, name, country_code)
VALUES
  ('MX-AGU', 'Aguascalientes', 'mx'),
  ('MX-BCN', 'Baja California', 'mx'),
  ('MX-BCS', 'Baja California Sur', 'mx'),
  ('MX-CAM', 'Campeche', 'mx'),
  ('MX-CHP', 'Chiapas', 'mx'),
  ('MX-CHH', 'Chihuahua', 'mx'),
  ('MX-COA', 'Coahuila', 'mx'),
  ('MX-COL', 'Colima', 'mx'),
  ('MX-DUR', 'Durango', 'mx'),
  ('MX-GUA', 'Guanajuato', 'mx'),
  ('MX-GRO', 'Guerrero', 'mx'),
  ('MX-HID', 'Hidalgo', 'mx'),
  ('MX-JAL', 'Jalisco', 'mx'),
  ('MX-MEX', 'State of Mexico', 'mx'),
  ('MX-MIC', 'Michoacán', 'mx'),
  ('MX-MOR', 'Morelos', 'mx'),
  ('MX-NAY', 'Nayarit', 'mx'),
  ('MX-NLE', 'Nuevo León', 'mx'),
  ('MX-OAX', 'Oaxaca', 'mx'),
  ('MX-PUE', 'Puebla', 'mx'),
  ('MX-QUE', 'Querétaro', 'mx'),
  ('MX-ROO', 'Quintana Roo', 'mx'),
  ('MX-SLP', 'San Luis Potosí', 'mx'),
  ('MX-SIN', 'Sinaloa', 'mx'),
  ('MX-SON', 'Sonora', 'mx'),
  ('MX-TAB', 'Tabasco', 'mx'),
  ('MX-TAM', 'Tamaulipas', 'mx'),
  ('MX-TLA', 'Tlaxcala', 'mx'),
  ('MX-VER', 'Veracruz', 'mx'),
  ('MX-YUC', 'Yucatán', 'mx'),
  ('MX-ZAC', 'Zacatecas', 'mx')

ON CONFLICT (id) DO NOTHING;
