INSERT INTO "worldTravelCountryRegions" (id, name, country_code)
VALUES
  ('IN-AN', 'Andaman and Nicobar Islands', 'in'),
  ('IN-AP', 'Andhra Pradesh', 'in'),
  ('IN-AR', 'Arunachal Pradesh', 'in'),
  ('IN-AS', 'Assam', 'in'),
  ('IN-BR', 'Bihar', 'in'),
  ('IN-CH', 'Chandigarh', 'in'),
  ('IN-CT', 'Chhattisgarh', 'in'),
  ('IN-DN', 'Dadra and Nagar Haveli and Daman and Diu', 'in'),
  ('IN-DD', 'Daman and Diu', 'in'),  -- These IDs are consolidated now, but adding separately for compatibility
  ('IN-DL', 'Delhi', 'in'),
  ('IN-GA', 'Goa', 'in'),
  ('IN-GJ', 'Gujarat', 'in'),
  ('IN-HR', 'Haryana', 'in'),
  ('IN-HP', 'Himachal Pradesh', 'in'),
  ('IN-JH', 'Jharkhand', 'in'),
  ('IN-KA', 'Karnataka', 'in'),
  ('IN-KL', 'Kerala', 'in'),
  ('IN-LD', 'Lakshadweep', 'in'),
  ('IN-MP', 'Madhya Pradesh', 'in'),
  ('IN-MH', 'Maharashtra', 'in'),
  ('IN-MN', 'Manipur', 'in'),
  ('IN-ML', 'Meghalaya', 'in'),
  ('IN-MZ', 'Mizoram', 'in'),
  ('IN-NL', 'Nagaland', 'in'),
  ('IN-OR', 'Odisha', 'in'),
  ('IN-PY', 'Puducherry', 'in'),
  ('IN-PB', 'Punjab', 'in'),
  ('IN-RJ', 'Rajasthan', 'in'),
  ('IN-SK', 'Sikkim', 'in'),
  ('IN-TN', 'Tamil Nadu', 'in'),
  ('IN-TG', 'Telangana', 'in'),
  ('IN-TR', 'Tripura', 'in'),
  ('IN-UP', 'Uttar Pradesh', 'in'),
  ('IN-UT', 'Uttarakhand', 'in'),
  ('IN-WB', 'West Bengal', 'in')

ON CONFLICT (id) DO NOTHING;
