name: Build and push beta images

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-images.yml
    with:
      tag: beta
      filter_paths: true
    secrets: inherit
